spark:
  app_name: "mm"
  files:
    max_partition_bytes: 67108864
  driver:
    memory: "50g"
    max_result_size: "2g"
  loglevel: "ERROR"


path:
  wd: "/Users/luciomelito/Documents/GD/cider/"
  featurizer:
    data: "/Users/luciomelito/Documents/GD/cider/synthetic_data"
    outputs: "/Users/luciomelito/Documents/GD/cider/outputs/featurizer"
    file_names:
      cdr: '/cdr.csv'
      antennas: '/antennas.csv'
      recharges: '/recharges.csv'
      mobiledata: '/mobiledata.csv'
      mobilemoney: '/mobilemoney.csv'
      shapefiles:
        'regions': '/regions.geojson'
        'prefectures': '/prefectures.geojson'
  ml:
    outputs: "/Users/luciomelito/Documents/GD/cider/outputs/machinelearning"
    features: '/Users/luciomelito/Documents/GD/cider/outputs/featurizer/datasets/features.csv'
    labels: "/Users/luciomelito/Documents/GD/cider/synthetic_data/labels_v2.csv"
  home_location:
    data: "/Users/luciomelito/Documents/GD/cider/synthetic_data"
    outputs: "/Users/luciomelito/Documents/GD/cider/outputs/homelocation"
    file_names:
      cdr: '/cdr.csv'
      antennas: '/antennas.csv'
      shapefiles:
        'prefectures': '/prefectures.geojson'
      poverty_scores: null
      groundtruth: '/home_locations.csv'


col_names:
  cdr:
    txn_type: "txn_type"
    caller_id: "caller_id"
    recipient_id: "recipient_id"
    timestamp: "timestamp"
    duration: "duration"
    caller_antenna: "caller_antenna"
    recipient_antenna: "recipient_antenna"
    international: "international"
  antennas:
    antenna_id: "antenna_id"
    tower_id: "tower_id"
    latitude: "latitude"
    longitude: "longitude"
  recharges:
    caller_id: "caller_id"
    amount: "amount"
    timestamp: "timestamp"
  mobiledata:
    caller_id: "caller_id"
    volume: "volume"
    timestamp: "timestamp"
  mobilemoney:
    txn_type: "txn_type"
    caller_id: "caller_id"
    recipient_id: "recipient_id"
    timestamp: "timestamp"
    amount: "amount"
    sender_balance_before: "sender_balance_before"
    sender_balance_after: "sender_balance_after"
    recipient_balance_before: "recipient_balance_before"
    recipient_balance_after: "recipient_balance_after"
  geo: 'tower_id'


params:
  home_location:
    filter_hours: null
  automl:
    time_left: 900
    n_jobs: 1
    memory_limit: 3072


hyperparams:
  'linear':
    'dropmissing__threshold': [0.9, 1]
    'droplowvariance__threshold': [ 0, 0.01 ]
    'winsorizer__limits': [!!python/tuple [0., 1.], !!python/tuple [0.005, .995]]
  'lasso':
    'dropmissing__threshold': [ 0.9, 1 ]
    'droplowvariance__threshold': [ 0, 0.01 ]
    'winsorizer__limits': [!!python/tuple [0., 1.], !!python/tuple [0.005, .995]]
    'model__alpha': [ .001, .01, .05, .03, .1 ]
  'ridge':
    'dropmissing__threshold': [ 0.9, 1 ]
    'droplowvariance__threshold': [ 0, 0.01 ]
    'winsorizer__limits': [!!python/tuple [0., 1.], !!python/tuple [0.005, .995]]
    'model__alpha': [ .001, .01, .05, .03, .1 ]
  'randomforest':
    'dropmissing__threshold': [ 0.9, 1 ]
    'droplowvariance__threshold': [ 0, 0.01 ]
    'winsorizer__limits': [!!python/tuple [0., 1.], !!python/tuple [0.005, .995]]
    'model__max_depth': [ 2, 4, 6, 8, 10 ]
    'model__n_estimators': [ 50, 100, 200 ]
  'gradientboosting':
    'dropmissing__threshold': [ 0.99 ]
    'droplowvariance__threshold': [ 0.01 ]
    'winsorizer__limits': [!!python/tuple [0., 1.], !!python/tuple [0.005, .995]]
    'model__min_data_in_leaf': [ 10, 20, 50 ]
    'model__num_leaves': [ 5, 10, 20 ]
    'model__learning_rate': [ 0.05, 0.075, 0.1 ]
    'model__n_estimators': [ 50, 100, 200 ]